name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files via SCP
      run: |
        sudo apt install sshpass
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/andrewthecoder/

    - name: Install dependencies, build, and restart app with PM2
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          cd /var/www/andrewthecoder
          npm install
          npm run astro build

